# Generated by Django 5.1.6 on 2025-03-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_category_my_order_comment_my_order_order_my_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['my_order']},
        ),
    ]
